name: Generate Neon Butterfly Animation

on:
  schedule:
    - cron: "0 */12 * * *"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Generate butterfly.svg
        run: |
          mkdir -p dist
          cat > dist/butterfly.svg << 'EOF'
          <svg width="800" height="200" viewBox="0 0 800 200" xmlns="http://www.w3.org/2000/svg">
            <defs>
              <radialGradient id="wingGradient" cx="50%" cy="50%" r="50%">
                <stop offset="0%" stop-color="#ff00ff" stop-opacity="1"/>
                <stop offset="100%" stop-color="#00ffff" stop-opacity="0.4"/>
              </radialGradient>
            </defs>

            <rect width="100%" height="100%" fill="#0a0a0a"/>

            <!-- Neon Butterflies -->
            <g>
              <g transform="translate(150,100)">
                <ellipse rx="45" ry="25" fill="url(#wingGradient)">
                  <animate attributeName="rx" values="45;55;45" dur="4s" repeatCount="indefinite"/>
                </ellipse>
                <ellipse rx="45" ry="25" fill="url(#wingGradient)" transform="rotate(180)">
                  <animate attributeName="rx" values="45;55;45" dur="4s" repeatCount="indefinite"/>
                </ellipse>
                <circle r="6" fill="#ffffff"/>
              </g>

              <g transform="translate(400,80)">
                <ellipse rx="35" ry="20" fill="url(#wingGradient)">
                  <animate attributeName="rx" values="35;45;35" dur="3s" repeatCount="indefinite"/>
                </ellipse>
                <ellipse rx="35" ry="20" fill="url(#wingGradient)" transform="rotate(180)">
                  <animate attributeName="rx" values="35;45;35" dur="3s" repeatCount="indefinite"/>
                </ellipse>
                <circle r="5" fill="#ffffff"/>
              </g>

              <g transform="translate(650,120)">
                <ellipse rx="40" ry="22" fill="url(#wingGradient)">
                  <animate attributeName="rx" values="40;50;40" dur="3.5s" repeatCount="indefinite"/>
                </ellipse>
                <ellipse rx="40" ry="22" fill="url(#wingGradient)" transform="rotate(180)">
                  <animate attributeName="rx" values="40;50;40" dur="3.5s" repeatCount="indefinite"/>
                </ellipse>
                <circle r="5" fill="#ffffff"/>
              </g>
            </g>
          </svg>
          EOF

      - name: Deploy to output branch
        uses: crazy-max/ghaction-github-pages@v3
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
